[versions]
appcompat = "1.6.1"
material = "1.11.0"
recyclerview = "1.3.2"
corektx = "1.12.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
